name: UndefinedWorldItem
version: 1.0-SNAPSHOT
main: org.red.minecraft.uw.item.UndefinedWorldItemPlugin
authors: [RedKiller]
api-version: 26.1
depend:
- CommediaDellarte
- UndefinedWorldCore
- Nexo

commands:
  test:
    usage: "/test"
  ugive:
    usage: "/ugive <아이템ID> [수량]"
    aliases: [ug]
    permission: op