name: UndefinedWorldItem
version: 1.0-SNAPSHOT
main: org.red.minecraft.uw.item.UndefinedWorldItemPlugin
authors: [RedKiller]
api-version: 26.1
depend:
- CommediaDellarte
- UndefinedWorldCore

commands:
  test:
    usage: "/test"