<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>org.red.minecraft</groupId>
    <artifactId>uw</artifactId>
    <version>1.0-SNAPSHOT</version>
  </parent>
  <groupId>org.red.minecraft.uw</groupId>
  <artifactId>item</artifactId>
  <packaging>jar</packaging>
  <name>UndefinedWorldPlugin Item</name>

  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-deploy-plugin</artifactId>
        <version>3.1.1</version>
        <configuration>
          <skip>false</skip>
        </configuration>
      </plugin>
    </plugins>
  </build>

  <dependencies>
    <dependency>
      <groupId>org.jetbrains</groupId>
      <artifactId>annotations</artifactId>
      <version>20.1.0</version>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>io.papermc.paper</groupId>
      <artifactId>paper-api</artifactId>
      <version>${papermc-api.version}</version>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.red.minecraft.dellarte</groupId>
      <artifactId>library</artifactId>
      <version>3.1-SNAPSHOT</version>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>com.nexomc</groupId>
      <artifactId>nexo</artifactId>
      <version>1.23</version>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.red.minecraft.uw</groupId>
      <artifactId>core</artifactId>
      <version>${uw.version}</version>
      <scope>provided</scope>
    </dependency>
  </dependencies>
</project>
