name: UndefinedWorldCore
version: 1.0-SNAPSHOT
main: org.red.minecraft.uw.core.UndefinedWorldCorePlugin
authors: [RedKiller]
api-version: 26.1
depend:
- CommediaDellarte
- PlaceholderAPI

commands:
  stat:
  equipment:
    aliases: [equip, eq]
  skill:
  skillcraft:
    aliases: [sc]
